crm_project/crm_project/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import home, about, logout_user
from authentication.views import registration


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home,name='home'),
    path('about/', about, name='about'),
    path('registrations/', registration, name='registrations'),
    path('login/', views.LoginView.as_view(template_name='crm_project/login.html'),name='login'),
    path('logout/', logout_user, name='logout'),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/product/', include('product.urls')),
    path('dashboard/customer/', include('customer.urls'))

]

crm_project/dashboard/urls.py
from django.urls import path
from .views import dashboard


urlpatterns = [path('', dashboard, name='dashboard')]

crm_project/product/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('', product_list, name='product_list'),
    path('add-product/',add_product,name='add_product'),
    path('<int:pk>/', product_detail, name='product_detail'),
    path('<int:pk>/update/', product_update, name='product_update'),
    path('<int:pk>/delete/', product_delete,name='product_delete'),
    path('<int:pk>/update_time/', update_time,name='update_time')
    
    ]

crm_project/dashboard/models.py
from django.db import models

# Create your models here.

crm_project/product/models.py
from django.db import models

from customer.models import Customer
from authentication.models import User


TYPE_CHOICE = [('повеска','подвеска'), 
               ('кольцо','кольцо'),
               ('брошь','брошь'), 
               ('серьги','серьги'), 
               ('комплект', 'комплект'),
               ('пусеты', 'пусеты'), 
               ('другое', 'другое'),
               ('колье','колье'),
               ('браслет','браслет')
               ]
STATUS_CHOICE = (('1','принят'),
    ("2","в работе"),
    ("4","правки"),
    ("3","согласование"),
    ("5", "на росте"),
    ("6","выполнен")
)
# MANAGER_CHOICE = sorted([(i.id, f'{i.last_name} {i.first_name}') for i in User.objects.filter(role = "manager")])
# MANAGER_CHOICE = sorted([(i.id, f'{i.last_name} {i.first_name}') for i in User.objects.filter(role = "manager")])
# WORKER_CHOICE = sorted([(int(i.id), f'{i.last_name} {i.first_name}') for i in User.objects.filter(role = "3d")])
# WORKER_CHOICE = sorted([(i.id, f'{i.last_name} {i.first_name}') for i in User.objects.filter(role = "3d")])

class Product(models.Model):

    name = models.CharField(max_length=100)
    created_by = models.ForeignKey(User, related_name='product',on_delete=models.CASCADE,null=True)
    on_work = models.BooleanField(default=False,null=True)
    worker = models.ForeignKey(User,related_name='worker', null=True,on_delete=models.CASCADE)
    work_time = models.TextField(max_length=200,default='00 дней 00 часов 00 минут', null=True)
    type_product = models.CharField(max_length=30,choices=TYPE_CHOICE,default='кольцо')
    customer = models.ForeignKey(Customer,related_name='customer', on_delete=models.CASCADE)
    price = models.IntegerField()
    create_date = models.DateTimeField(auto_now_add=True)
    start_date = models.DateTimeField(auto_created=False, null=True)
    expiration_date = models.DateField(auto_created=False)
    comment = models.TextField()
    status = models.CharField(max_length=20,choices=STATUS_CHOICE,null=True,default='1')

    
    def __str__(self):
        return f'{self.name} {self.start_date} {self.status}'

crm_project/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from product.models import Product
from customer.models import Customer



@login_required
def dashboard(request):

    products = Product.objects.all()
    

    customers = Customer.objects.all()

    if request.user.role == '3d':

        products = Product.objects.filter(worker_id = request.user.id)
        return render(request, 'dashboard/dashboard-3d.html', {'products': products,
                                                        })
    else:
        
        return render(request, 'dashboard/dashboard-manager.html', {'products': products,
                                                        'customers': customers})

# Create your views here.

crm_project/templates/dashboard/dashboard-3d.html
{% extends 'crm_project/base.html'%}

{%block title%}Dashboard{%endblock%}

{% block content%}
    <h1 class="text-xl">Dashboard</h1>

    <div class="py-6 px-6">
        
        <div class=" mt-6 flex justify-between">
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Название</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Создан</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Начат</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Дата сдачи</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Статус</p>
        </div>
        {% for product in products%}
            <div class="flex justify-between">
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">
                    <a href="{% url 'product_detail' product.id%}">{{product.name}}</a>
                </p> 
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.create_date}}</p>
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.start_date}}</p>
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.expiration_date}}</p>
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.get_status_display}}</p>

                <form method="post" action="{% url 'product_update' product.id%}">
                    {% csrf_token%}
                    <button class="py-4 px-8 bg-teal-500 text-white rounded-xl" type="submit">Update</button>
                </form>
            </div>  
            

        {%endfor%}
    
    </div>

{% endblock%}

crm_project/templates/dashboard/dashboard-manager.html
{% extends 'crm_project/base.html'%}

{%block title%}Dashboard{%endblock%}

{% block content%}
    <h1 class="text-xl">Dashboard</h1>

    <div class="py-6 px-6">
        <h1 class=" mb-4 text-xl">Заказы</h1>

        <div class=" mt-6 flex justify-between">
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Название</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Создан</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Начат</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Дата сдачи</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Статус</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Исполнитель</p>
        </div>
        
        {% for product in products%}
            <div class="flex justify-between">
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">
                    <a href="{% url 'product_detail' product.id%}">{{product.name}}</a>
                </p> 
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.create_date}}</p>
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.start_date}}</p>
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.expiration_date}}</p>
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.get_status_display}}</p>
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.get_worker_display}}</p>

                <form method="post" action="{% url 'product_update' product.id%}">
                    {% csrf_token%}
                    <button class="py-4 px-8 bg-teal-500 text-white rounded-xl" type="submit">Update</button>
                </form>
            </div>  
            {%endfor%}
    
     </div>        
            <div class="py-6 px-6">
                <h1 class=" mb-4 text-xl">Заказчики</h1>
               
                <div class=" mt-6 flex justify-between">
                    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">ФИО</p>
                    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Контактный телефон</p>
                    
                </div>
        {% for customer in customers %}
            <div class="flex justify-between">
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">
                    <a href="{% url 'customer_detail' customer.id%}">{{customer.name}}</a>
                </p> 
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{customer.phone_number}}</p>
            </div>

        {%endfor%}
        
        
    </div>

{% endblock%}

crm_project/templates/dashboard/dashboard.html
{% extends 'crm_project/base.html'%}

{%block title%}Dashboard{%endblock%}

{% block content%}
    <h1 class="text-xl">Dashboard</h1>

    <div class="py-6 px-6">
        
        <div class=" mt-6 flex justify-between">
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Название</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Создан</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Начат</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Дата сдачи</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Статус</p>
        </div>

        {% for product in products%}
            <div class="flex justify-between">
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">
                    <a href="{% url 'product_detail' product.id%}">{{product.name}}</a>
                </p> 
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.create_date}}</p>
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.start_date}}</p>
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.expiration_date}}</p>
                <p class="py-4 px-2 font-semibold w-full bg-gray-100">{{product.get_status_display}}</p>

                <form method="post" action="{% url 'product_update' product.id%}">
                    {% csrf_token%}
                    <button class="py-4 px-8 bg-teal-500 text-white rounded-xl" type="submit">Update</button>
                </form>
            </div>                                                      
        {%endfor%}
    </div>

{% endblock%}